os: linux
dist: bionic

language: cpp

addons:
  apt:
    packages:
      - build-essential
      - ocaml 
      - ocamlbuild
      - automake
      - autoconf
      - libtool
      - wget
      - python
      - python3 
      - python3-pip
      - libssl-dev
      - git
      - cmake
      - perl
      - libssl-dev
      - libcurl4-openssl-dev
      - protobuf-compiler
      - libprotobuf-dev
      - debhelper
      - reprepro
      - unzip
      - libboost-dev

notifications:
  email: true

jobs: # Add two jobs for each type of paper test, for each SDK
  include:
    - name: "Table 1 - Patched SDK"
      script: ./sdk_helper.sh install_patched && source ./sdk_helper.sh patched && cd 01_table1_basic-poc && ./eval_simulator.sh
    - name: "Table 1 - Vulnerable SDK"
      script: ./sdk_helper.sh install_vulnerable && source ./sdk_helper.sh vulnerable && cd 01_table1_basic-poc && ./eval_simulator.sh