os: linux
dist: bionic

notifications:
  email: true

services:
  - docker

# submodules will be pulled in the Docker container
git:
  submodules: false

language: c

script:
  - docker run --name docker-ci-run -d -h "badf1oa7" -t sgx-fpu
  - docker exec docker-ci-run /bin/bash -c "$SCRIPT"
  - docker ps -a

# Add two jobs for each type of paper test, for each SDK
jobs:
  include:
    - name: "Build SGX simulator"
      stage: build-sim
      script: make build
    - name: "Table 1 - Patched SDK"
      stage: run-sim
      env: SCRIPT="./sdk_helper.sh install_patched && source ./sdk_helper.sh patched && cd 01_table1_basic-poc && ./eval_simulator.sh"
    - name: "Table 1 - Vulnerable SDK"
      env: SCRIPT="./sdk_helper.sh install_vulnerable && source ./sdk_helper.sh vulnerable && cd 01_table1_basic-poc && ./eval_simulator.sh"
    - name: "Table 3 - Patched SDK (minimal run to not exceed Travis timeout)"
      env: SCRIPT="./sdk_helper.sh install_patched && source ./sdk_helper.sh patched && cd 04_section-5_mnist-javascript/eval/ && ./run_tests.py --simulator --mnist ../js-files/mnist_handwritten_test_first5.json -a 5 && ./eval.py -p $(ls -a | grep SIM)"
    - name: "Table 3 - Vulnerable SDK (minimal run to not exceed Travis timeout)"
      env: SCRIPT="./sdk_helper.sh install_vulnerable && source ./sdk_helper.sh vulnerable && cd 04_section-5_mnist-javascript/eval/ && ./run_tests.py --simulator --mnist ../js-files/mnist_handwritten_test_first5.json -a 5 && ./eval.py -p $(ls -a | grep SIM)"
